<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/22
 * Time: 10:38
 */

namespace app\modules\api\controllers;

use app\modules\api\common\ApiController;

class TestController extends ApiController
{
    public function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionTest()
    {
        $str = <<<str
        <caption>视频上传/展示</caption>
    <thead>
    <td>
        <form enctype="multipart/form-data" method="post" action="http://video.yaoyuefu.com/api/soupfile/filevideo">
            <input type="hidden" name="aid" value="10">
            <input type="hidden" name="callbackurl" value="http://yyytest.xianhuahua.com/new/notifyvideo">
            <input type="hidden" name="requestid" value="cg9cSQ3rChpyh7Bqq2fMTeNZ5SfXTjZX">
            <input type="file" name="files" placeholder="点击选择文件">
            <input type="submit" value="上传视频">
        </form>
    </td>
    </thead>

str;
        echo $str;

    }
}